DROP DATABASE IF EXISTS GEST_EMPLE;
CREATE DATABASE GEST_EMPLE;
USE GEST_EMPLE;
CREATE TABLE ENTERPRISE(
id int PRIMARY KEY AUTO_INCREMENT,
enter_name VARCHAR(255) unique,
enter_passwd VARCHAR(255)
);

CREATE TABLE DEPT(
id int PRIMARY KEY AUTO_INCREMENT,
enterprise int REFERENCES ENTERPRISE(id),
dept_name VARCHAR(255),
dept_location VARCHAR(255)
);

CREATE TABLE EMPLE(
dni VARCHAR(9) PRIMARY KEY,
working_dept int REFERENCES DEPT(id),
emp_name VARCHAR(255),
emp_surname VARCHAR(255),
emp_salary DOUBLE,
emp_date_join DATE
);